#iso_url: "https://download.fedoraproject.org/pub/fedora/linux/releases/39/Server/x86_64/iso/Fedora-Server-dvd-x86_64-39-1.5.iso" # Fedora 39
iso_url: "https://download.fedoraproject.org/pub/fedora/linux/releases/41/Server/x86_64/iso/Fedora-Server-dvd-x86_64-41-1.4.iso" # Fedora 41
#iso_checksum: "sha256:2755cdff6ac6365c75be60334bf1935ade838fc18de53d4c640a13d3e904f6e9" # Fedora 39
iso_checksum: "sha256:6037e489103401a6ad4e54a4bcb2df7525693bdc3f2ce4aa895838b65647e551"
timezone: America/Los_Angeles
dhcp_proxy: false
