elementweb:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: "homelab-tunnel.lab.pyrodactyl.dev"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    hosts:
      - host: &frontend_host chat.lab.pyrodactyl.dev
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: element-tls-certificate
        hosts:
          - *frontend_host
  config:
    default:
      base_url: https://matrix.lab.pyrodactyl.dev
      server_name: lab.pyrodactyl.dev

dendrite:
  dendrite_config:
    global:
      server_name: matrix.lab.pyrodactyl.dev
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hostName: matrix.lab.pyrodactyl.dev
    tls:
      - hosts:
          - matrix.lab.pyrodactyl.dev
        secretName: matrix-tls-certificate
  postgresql:
    enabled: true
